"""Validate source bundles and render certificate-backed knowledge documents."""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Sequence

from .compiler import CERTIFICATE_VERSION


DOCUMENT_VERSION = "1.0"

SOURCE_TYPES = {
    "RESEARCH",
    "OFFICIAL_DOCUMENTATION",
    "AUTHORITATIVE_GUIDANCE",
    "PRIMARY_EVIDENCE",
    "EXPERT_INTERPRETATION",
    "PRACTITIONER_EXPERIENCE",
    "ANECDOTE",
    "OPINION",
    "MARKETING",
    "UNKNOWN",
}

MEDIA_TYPES = {"VIDEO", "ARTICLE", "PAPER", "DOCUMENT", "DATASET", "OTHER"}

KNOWLEDGE_SOURCE_TYPES = {
    "RESEARCH",
    "OFFICIAL_DOCUMENTATION",
    "AUTHORITATIVE_GUIDANCE",
    "PRIMARY_EVIDENCE",
}

VIEWPOINT_SOURCE_TYPES = {
    "EXPERT_INTERPRETATION",
    "PRACTITIONER_EXPERIENCE",
    "ANECDOTE",
    "OPINION",
}

LAYERS = (
    "SUPPORTED_KNOWLEDGE",
    "CONDITIONAL_KNOWLEDGE",
    "SUPPORTED_COMPONENT",
    "PRACTICE_OR_VIEWPOINT",
    "DISPUTED_OR_UNRESOLVED",
    "REJECTED",
)

HEADINGS = {
    "zh-CN": {
        "question": "要回答的问题",
        "boundary": "材料边界",
        "summary": "编译结果概览",
        "sources_used": "来源",
        "status": "状态",
        "why": "为什么这样分类",
        "conditions": "适用条件",
        "limitations": "局限",
        "certificate": "证书",
        "open_questions": "仍未解决的问题",
        "source_ledger": "来源清单",
        "source_id": "来源 ID",
        "title": "标题",
        "type": "性质",
        "medium": "载体",
        "locator": "位置",
        "generated": "本文件由 KnowSift 根据逐条证书生成。未准入内容不会出现在知识结论中。",
        "layers": {
            "SUPPORTED_KNOWLEDGE": "有证据支持的知识",
            "CONDITIONAL_KNOWLEDGE": "有条件成立的知识",
            "SUPPORTED_COMPONENT": "原说法中可以保留的部分",
            "PRACTICE_OR_VIEWPOINT": "从业者经验、观点与个人叙述",
            "DISPUTED_OR_UNRESOLVED": "存在争议或证据不足的说法",
            "REJECTED": "被排除的说法",
        },
    },
    "en": {
        "question": "Question",
        "boundary": "Source boundary",
        "summary": "Compilation summary",
        "sources_used": "Sources",
        "status": "Status",
        "why": "Why it is classified this way",
        "conditions": "Conditions",
        "limitations": "Limitations",
        "certificate": "Certificate",
        "open_questions": "Open questions",
        "source_ledger": "Source ledger",
        "source_id": "Source ID",
        "title": "Title",
        "type": "Role",
        "medium": "Medium",
        "locator": "Locator",
        "generated": "Generated by KnowSift from claim certificates. Non-admitted content is excluded from knowledge conclusions.",
        "layers": {
            "SUPPORTED_KNOWLEDGE": "Supported knowledge",
            "CONDITIONAL_KNOWLEDGE": "Conditional knowledge",
            "SUPPORTED_COMPONENT": "Supported parts of broader claims",
            "PRACTICE_OR_VIEWPOINT": "Practitioner reports, viewpoints, and anecdotes",
            "DISPUTED_OR_UNRESOLVED": "Disputed or unresolved claims",
            "REJECTED": "Excluded claims",
        },
    },
}


class KnowledgeDocumentError(ValueError):
    """Raised when a bundle or document plan violates the admission contract."""


def _require_mapping(value: Any, path: str) -> Mapping[str, Any]:
    if not isinstance(value, Mapping):
        raise KnowledgeDocumentError(f"{path}:must_be_object")
    return value


def _require_list(value: Any, path: str) -> Sequence[Any]:
    if not isinstance(value, list):
        raise KnowledgeDocumentError(f"{path}:must_be_array")
    return value


def _require_text(value: Any, path: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise KnowledgeDocumentError(f"{path}:must_be_nonempty_string")
    return value.strip()


def _reject_unknown_keys(data: Mapping[str, Any], allowed: Iterable[str], path: str) -> None:
    unknown = sorted(set(data) - set(allowed))
    if unknown:
        raise KnowledgeDocumentError(f"{path}:unknown_fields:{','.join(unknown)}")


def _resolve_local_path(base_dir: Path, relative: str, path: str) -> Path:
    candidate = (base_dir / relative).resolve()
    try:
        candidate.relative_to(base_dir.resolve())
    except ValueError as error:
        raise KnowledgeDocumentError(f"{path}:path_escapes_bundle") from error
    if not candidate.is_file():
        raise KnowledgeDocumentError(f"{path}:file_not_found:{relative}")
    return candidate


def validate_source_bundle(data: Any, base_dir: Path) -> Dict[str, Any]:
    """Validate a source bundle prepared by an external collection agent."""

    root = _require_mapping(data, "bundle")
    _reject_unknown_keys(
        root,
        {
            "bundle_version",
            "topic",
            "question",
            "language",
            "source_boundary",
            "sources",
        },
        "bundle",
    )
    if root.get("bundle_version") != DOCUMENT_VERSION:
        raise KnowledgeDocumentError("bundle.bundle_version:must_equal_1.0")
    language = root.get("language", "zh-CN")
    if language not in HEADINGS:
        raise KnowledgeDocumentError("bundle.language:unsupported")
    normalized: Dict[str, Any] = {
        "bundle_version": DOCUMENT_VERSION,
        "topic": _require_text(root.get("topic"), "bundle.topic"),
        "question": _require_text(root.get("question"), "bundle.question"),
        "language": language,
        "source_boundary": _require_text(
            root.get("source_boundary"), "bundle.source_boundary"
        ),
        "sources": [],
    }

    sources = _require_list(root.get("sources"), "bundle.sources")
    if not sources:
        raise KnowledgeDocumentError("bundle.sources:must_not_be_empty")
    source_ids = set()
    for index, raw_source in enumerate(sources):
        path = f"bundle.sources[{index}]"
        source = _require_mapping(raw_source, path)
        _reject_unknown_keys(
            source,
            {
                "source_id",
                "title",
                "source_type",
                "medium",
                "locator",
                "author",
                "published_at",
                "captured_at",
                "content",
                "content_path",
                "notes",
            },
            path,
        )
        source_id = _require_text(source.get("source_id"), f"{path}.source_id")
        if source_id in source_ids:
            raise KnowledgeDocumentError(f"{path}.source_id:duplicate:{source_id}")
        source_ids.add(source_id)
        source_type = source.get("source_type")
        if source_type not in SOURCE_TYPES:
            raise KnowledgeDocumentError(f"{path}.source_type:unsupported")
        medium = source.get("medium")
        if medium not in MEDIA_TYPES:
            raise KnowledgeDocumentError(f"{path}.medium:unsupported")
        has_content = isinstance(source.get("content"), str) and bool(
            source.get("content", "").strip()
        )
        has_path = isinstance(source.get("content_path"), str) and bool(
            source.get("content_path", "").strip()
        )
        if has_content == has_path:
            raise KnowledgeDocumentError(
                f"{path}:exactly_one_of_content_or_content_path_required"
            )
        normalized_source = dict(source)
        normalized_source["source_id"] = source_id
        normalized_source["title"] = _require_text(source.get("title"), f"{path}.title")
        normalized_source["locator"] = _require_text(
            source.get("locator"), f"{path}.locator"
        )
        if has_path:
            _resolve_local_path(base_dir, source["content_path"], f"{path}.content_path")
        normalized["sources"].append(normalized_source)
    return normalized


def _load_certificate(base_dir: Path, relative: str, path: str) -> Mapping[str, Any]:
    certificate_path = _resolve_local_path(base_dir, relative, path)
    try:
        certificate = json.loads(certificate_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise KnowledgeDocumentError(f"{path}:invalid_certificate_json") from error
    certificate = _require_mapping(certificate, path)
    if certificate.get("certificate_version") != CERTIFICATE_VERSION:
        raise KnowledgeDocumentError(f"{path}:certificate_version_mismatch")
    return certificate


def _certificate_source_ids(certificate: Mapping[str, Any]) -> set[str]:
    result = set()
    for reference in certificate.get("evidence_references", []):
        if isinstance(reference, Mapping) and isinstance(reference.get("source_id"), str):
            result.add(reference["source_id"])
    return result


def _validate_record_layer(
    record: Mapping[str, Any],
    certificate: Mapping[str, Any],
    source_types: set[str],
    path: str,
) -> None:
    layer = record["layer"]
    admission = certificate.get("admission")
    text = record["text"]
    canonical = certificate.get("canonical_claim")

    if layer == "SUPPORTED_KNOWLEDGE":
        if admission != "ADMIT" or text != canonical:
            raise KnowledgeDocumentError(f"{path}:supported_layer_requires_exact_admit")
        if not (source_types & KNOWLEDGE_SOURCE_TYPES):
            raise KnowledgeDocumentError(f"{path}:knowledge_layer_requires_knowledge_source")
    elif layer == "CONDITIONAL_KNOWLEDGE":
        if admission != "ADMIT_SCOPED" or text != canonical:
            raise KnowledgeDocumentError(
                f"{path}:conditional_layer_requires_exact_scoped_claim"
            )
        if not (source_types & KNOWLEDGE_SOURCE_TYPES):
            raise KnowledgeDocumentError(f"{path}:knowledge_layer_requires_knowledge_source")
    elif layer == "SUPPORTED_COMPONENT":
        if admission != "ADMIT_COMPONENTS_ONLY":
            raise KnowledgeDocumentError(f"{path}:component_layer_requires_components_only")
        components = certificate.get("supported_components", [])
        component_id = record.get("component_id")
        match = any(
            isinstance(component, Mapping)
            and component.get("component_id") == component_id
            and component.get("text") == text
            for component in components
        )
        if not match:
            raise KnowledgeDocumentError(f"{path}:component_text_or_id_not_certified")
        if not (source_types & KNOWLEDGE_SOURCE_TYPES):
            raise KnowledgeDocumentError(f"{path}:knowledge_layer_requires_knowledge_source")
    elif layer == "PRACTICE_OR_VIEWPOINT":
        normalized_ir = certificate.get("normalized_ir")
        if admission not in {"ADMIT", "ADMIT_SCOPED"} or text != canonical:
            raise KnowledgeDocumentError(f"{path}:viewpoint_layer_requires_admitted_attestation")
        if not isinstance(normalized_ir, Mapping) or normalized_ir.get("operator") != "OBSERVE":
            raise KnowledgeDocumentError(f"{path}:viewpoint_layer_requires_observe_operator")
        if not source_types or not source_types.issubset(VIEWPOINT_SOURCE_TYPES):
            raise KnowledgeDocumentError(f"{path}:viewpoint_layer_source_type_mismatch")
    elif layer == "DISPUTED_OR_UNRESOLVED":
        if admission != "HOLD" or text != certificate.get("claim_text"):
            raise KnowledgeDocumentError(
                f"{path}:disputed_layer_requires_exact_held_claim"
            )
    elif layer == "REJECTED":
        if admission != "REJECT" or text != certificate.get("claim_text"):
            raise KnowledgeDocumentError(
                f"{path}:rejected_layer_requires_exact_rejected_claim"
            )
    else:
        raise KnowledgeDocumentError(f"{path}.layer:unsupported")


def validate_document_plan(data: Any, base_dir: Path) -> Dict[str, Any]:
    root = _require_mapping(data, "document")
    _reject_unknown_keys(
        root,
        {
            "document_version",
            "title",
            "question",
            "language",
            "source_boundary",
            "sources",
            "records",
            "open_questions",
        },
        "document",
    )
    if root.get("document_version") != DOCUMENT_VERSION:
        raise KnowledgeDocumentError("document.document_version:must_equal_1.0")
    language = root.get("language", "zh-CN")
    if language not in HEADINGS:
        raise KnowledgeDocumentError("document.language:unsupported")

    sources_raw = _require_list(root.get("sources"), "document.sources")
    sources: Dict[str, Dict[str, str]] = {}
    normalized_sources: List[Dict[str, str]] = []
    for index, raw_source in enumerate(sources_raw):
        path = f"document.sources[{index}]"
        source = _require_mapping(raw_source, path)
        _reject_unknown_keys(
            source,
            {"source_id", "title", "source_type", "medium", "locator"},
            path,
        )
        source_id = _require_text(source.get("source_id"), f"{path}.source_id")
        if source_id in sources:
            raise KnowledgeDocumentError(f"{path}.source_id:duplicate:{source_id}")
        source_type = source.get("source_type")
        if source_type not in SOURCE_TYPES:
            raise KnowledgeDocumentError(f"{path}.source_type:unsupported")
        medium = source.get("medium")
        if medium not in MEDIA_TYPES:
            raise KnowledgeDocumentError(f"{path}.medium:unsupported")
        normalized_source = {
            "source_id": source_id,
            "title": _require_text(source.get("title"), f"{path}.title"),
            "source_type": source_type,
            "medium": medium,
            "locator": _require_text(source.get("locator"), f"{path}.locator"),
        }
        sources[source_id] = normalized_source
        normalized_sources.append(normalized_source)

    records_raw = _require_list(root.get("records"), "document.records")
    if not records_raw:
        raise KnowledgeDocumentError("document.records:must_not_be_empty")
    record_ids = set()
    normalized_records = []
    for index, raw_record in enumerate(records_raw):
        path = f"document.records[{index}]"
        record = _require_mapping(raw_record, path)
        _reject_unknown_keys(
            record,
            {
                "record_id",
                "topic",
                "layer",
                "text",
                "explanation",
                "source_ids",
                "conditions",
                "limitations",
                "certificate_file",
                "component_id",
            },
            path,
        )
        record_id = _require_text(record.get("record_id"), f"{path}.record_id")
        if record_id in record_ids:
            raise KnowledgeDocumentError(f"{path}.record_id:duplicate:{record_id}")
        record_ids.add(record_id)
        layer = record.get("layer")
        if layer not in LAYERS:
            raise KnowledgeDocumentError(f"{path}.layer:unsupported")
        source_ids_raw = _require_list(record.get("source_ids"), f"{path}.source_ids")
        source_ids = []
        for source_id in source_ids_raw:
            source_id = _require_text(source_id, f"{path}.source_ids[]")
            if source_id not in sources:
                raise KnowledgeDocumentError(f"{path}.source_ids:unknown:{source_id}")
            source_ids.append(source_id)
        certificate_file = _require_text(
            record.get("certificate_file"), f"{path}.certificate_file"
        )
        certificate = _load_certificate(base_dir, certificate_file, f"{path}.certificate_file")
        certificate_sources = _certificate_source_ids(certificate)
        if not set(source_ids).issubset(certificate_sources):
            raise KnowledgeDocumentError(f"{path}.source_ids:not_backed_by_certificate")
        source_types = {sources[source_id]["source_type"] for source_id in source_ids}

        normalized_record = {
            "record_id": record_id,
            "topic": _require_text(record.get("topic"), f"{path}.topic"),
            "layer": layer,
            "text": _require_text(record.get("text"), f"{path}.text"),
            "explanation": _require_text(
                record.get("explanation"), f"{path}.explanation"
            ),
            "source_ids": source_ids,
            "conditions": [
                _require_text(item, f"{path}.conditions[]")
                for item in _require_list(record.get("conditions", []), f"{path}.conditions")
            ],
            "limitations": [
                _require_text(item, f"{path}.limitations[]")
                for item in _require_list(record.get("limitations", []), f"{path}.limitations")
            ],
            "certificate_file": certificate_file,
        }
        if "component_id" in record:
            normalized_record["component_id"] = _require_text(
                record.get("component_id"), f"{path}.component_id"
            )
        _validate_record_layer(normalized_record, certificate, source_types, path)
        normalized_records.append(normalized_record)

    open_questions = [
        _require_text(item, "document.open_questions[]")
        for item in _require_list(root.get("open_questions", []), "document.open_questions")
    ]
    return {
        "document_version": DOCUMENT_VERSION,
        "title": _require_text(root.get("title"), "document.title"),
        "question": _require_text(root.get("question"), "document.question"),
        "language": language,
        "source_boundary": _require_text(
            root.get("source_boundary"), "document.source_boundary"
        ),
        "sources": normalized_sources,
        "records": normalized_records,
        "open_questions": open_questions,
    }


def _bullet_list(items: Sequence[str]) -> List[str]:
    return [f"  - {item}" for item in items]


def render_knowledge_document(data: Any, base_dir: Path) -> str:
    plan = validate_document_plan(data, base_dir)
    words = HEADINGS[plan["language"]]
    counts = Counter(record["layer"] for record in plan["records"])
    lines = [
        f"# {plan['title']}",
        "",
        f"> {words['generated']}",
        "",
        f"## {words['question']}",
        "",
        plan["question"],
        "",
        f"## {words['boundary']}",
        "",
        plan["source_boundary"],
        "",
        f"## {words['summary']}",
        "",
        f"| {words['status']} | # |",
        "|---|---:|",
    ]
    for layer in LAYERS:
        lines.append(f"| {words['layers'][layer]} | {counts[layer]} |")

    for layer in LAYERS:
        layer_records = [record for record in plan["records"] if record["layer"] == layer]
        if not layer_records:
            continue
        lines.extend(["", f"## {words['layers'][layer]}", ""])
        for record in layer_records:
            lines.extend(
                [
                    f"### {record['text']}",
                    "",
                    f"- **{words['status']}：** `{record['layer']}`",
                    f"- **{words['why']}：** {record['explanation']}",
                    f"- **{words['sources_used']}：** "
                    + ", ".join(f"`{source_id}`" for source_id in record["source_ids"]),
                ]
            )
            if record["conditions"]:
                lines.append(f"- **{words['conditions']}：**")
                lines.extend(_bullet_list(record["conditions"]))
            if record["limitations"]:
                lines.append(f"- **{words['limitations']}：**")
                lines.extend(_bullet_list(record["limitations"]))
            lines.extend(
                [
                    f"- **{words['certificate']}：** `{record['certificate_file']}`",
                    "",
                ]
            )

    if plan["open_questions"]:
        lines.extend([f"## {words['open_questions']}", ""])
        lines.extend(f"- {question}" for question in plan["open_questions"])
        lines.append("")

    lines.extend(
        [
            f"## {words['source_ledger']}",
            "",
            f"| {words['source_id']} | {words['title']} | {words['type']} | {words['medium']} | {words['locator']} |",
            "|---|---|---|---|---|",
        ]
    )
    for source in plan["sources"]:
        safe_title = source["title"].replace("|", "\\|")
        safe_locator = source["locator"].replace("|", "\\|")
        lines.append(
            f"| `{source['source_id']}` | {safe_title} | `{source['source_type']}` | "
            f"`{source['medium']}` | {safe_locator} |"
        )
    return "\n".join(lines).rstrip() + "\n"
